[package]
name = "calculate-money-in-leetcode-bank-1716"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3.30", features = [] }
